### ISSUE TITLE
RecentListPage -> ProductDetailPage 이동 기능

### ISSUE THREAD

**Issue by tTab1204** [six-sense/1_mrCamel_team1#9]
## 설명
상세 페이지 이동 기능 구현

## 할 일
- [x] 상세 페이지 이동 기능 구현 필요

## 일정
2021.07.30(금)

**Comment by tTab1204** [comment]
엇.. 제가 이 issue를 해결하고 merge가 된 상태인걸로 알고 있는데, 이 issue는 delete해도 될까요?

**Comment by yisu-kim** [comment]
네 확인했습니다. 삭제해주세요.

**Comment by tTab1204** [comment]
Delete 이슈가 어디있.. 일단 Close로 보냈습니다
